# Generated by Django 4.0.4 on 2022-06-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base_time_slot',
            fields=[
                ('base_time_slot_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveIntegerField(default=0)),
                ('time', models.PositiveIntegerField(default=0)),
                ('hourly_payroll', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='store_information',
            fields=[
                ('store_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('manager_name', models.CharField(max_length=200)),
                ('total_worker_num', models.PositiveIntegerField(default=0)),
                ('total_working_hours', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='work_type_setting',
            fields=[
                ('work_type_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('work_type_name', models.CharField(max_length=200)),
                ('hourly_payroll', models.PositiveIntegerField(default=0)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.store_information')),
            ],
        ),
        migrations.CreateModel(
            name='worker_information',
            fields=[
                ('worker_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('worker_name', models.CharField(max_length=200)),
                ('work_type', models.CharField(max_length=200)),
                ('working_hours', models.PositiveIntegerField(default=0)),
                ('available_hours', models.PositiveIntegerField(default=0)),
                ('work_status', models.CharField(choices=[('Y', 'Worker'), ('N', 'Applicant')], max_length=200)),
                ('worktype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.work_type_setting')),
            ],
        ),
        migrations.CreateModel(
            name='time_slot',
            fields=[
                ('time_slot_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=200)),
                ('locked', models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=200)),
                ('base_time_slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.base_time_slot')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.worker_information')),
            ],
        ),
        migrations.CreateModel(
            name='payroll_management',
            fields=[
                ('payroll_management_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(default=0)),
                ('month', models.PositiveIntegerField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')])),
                ('num_of_week', models.PositiveIntegerField(default=0)),
                ('weekly_working_hours', models.PositiveIntegerField(default=0)),
                ('extra_pay', models.PositiveIntegerField(default=0)),
                ('total_weekly_payroll', models.PositiveIntegerField(default=0)),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.worker_information')),
            ],
        ),
        migrations.AddField(
            model_name='base_time_slot',
            name='work_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.work_type_setting'),
        ),
    ]
