# Generated by Django 4.0.4 on 2022-06-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('login_pw', models.CharField(max_length=15)),
            ],
        ),
    ]
